### ISSUE TITLE
multilanguage_support not working for getUpdatePopup()

### ISSUE THREAD

**Issue by leonnicklas** [42coders/eu-cookie-consent#12]
I just saw the cool new feature where later updating the users settings were implemented. Very Nice feature!

BUT: I just found out that the multilanguage_support feature isn't working when trying to update the settings. Instead of showing all cookies in the current app_locale it just shows them in the default app_locale set in config/app.php!
If the cookie banner however isn't set at all and the popup shows for the first time everything works just fine.

Does anyone have an idea on how to solve this problem? I couldn't find a solution yet.

**Comment by leonnicklas** [comment]
@42coders do you have any suggestions?

**Comment by Max-Hutschenreiter** [comment]
I will lock into both issues today thanks for the reporting

**Comment by Max-Hutschenreiter** [comment]
Fixed in the v1.0.5 release thanks for letting me know about the bug.

**Comment by leonnicklas** [comment]
Thx for the new release BUT sadly the **multilanguage_support** still isn't working for me on **update_popup()**.
Any idea why it isn't working correctly. I couldn't find a way to get it to work. Hope you could help me out:)

**Comment by Max-Hutschenreiter** [comment]
How do you set the language? The popup HTML is received via an ajax call. Before was a bug inside that the language was not handled correctly in this ajax call. But I added it, and now it's working fine for me. The package uses the default Laravel __('') multilanguage function.

**Comment by leonnicklas** [comment]
I'm using the default Laravel multilanguage function but it's still not working for me:/
I'm also using a custom setLocale middleware as priority middleware to set the app language to the users preference... Maybe that has something to do with it...
